export const portfolioData = {
  name: "Ravi Sah",
  initials: "RS",
  title: "B.Tech Computer Science & Engineering",
  subtitle: "Machine Learning | Software Development | Cloud",
  studentId: "RA2311003012262",
  photo: "https://i.postimg.cc/6qNTkjcN/RA2311003012262.jpg",
  location: "Chennai, India",
  status: "Open to Opportunities",
  contact: {
    phone: "+91 9234614488",
    email: "rsahravi57@gmail.com",
    linkedin: "https://linkedin.com/in/ravi-sah",
    github: "https://github.com/sahravi63",
  },
  summary:
    "Computer Science undergraduate passionate about machine learning and software development. Proficient in Python, Java, and modern web frameworks with a strong foundation in algorithms and data structures. Motivated by solving complex problems and continuously expanding knowledge across AI, cloud, and full-stack engineering.",
  stats: [
    { value: "8.96", label: "CGPA" },
    { value: "4+", label: "Projects" },
    { value: "4", label: "Certifications" },
    { value: "2", label: "Awards" },
  ],
  education: {
    degree: "B.Tech in Computer Science and Engineering",
    institution: "SRM Institute of Science and Technology",
    duration: "06/2023 - 05/2027",
    cgpa: "8.96 / 10.00",
    location: "Chennai, Tamil Nadu",
    coursework: ["Data Structures", "Algorithms", "DBMS", "Python", "Statistics"],
  },
  experience: [
    {
      role: "AICTE Virtual Internship",
      org: "Government of India",
      duration: "2024",
      type: "Remote",
      points: [
        "Completed a government-recognized internship focused on software and cloud technologies.",
        "Applied development skills to solve real-world industrial problems.",
      ],
    },
  ],
  projects: [
    {
      name: "PDF Data Extraction System",
      date: "Aug 2024",
      tech: ["Python", "NLP"],
      iconKey: "file-text",
      accent: "cyan",
      github: "https://github.com/sahravi63/pdf-dataExtraction",
      live: "https://pdf-data-extraction-1av5.vercel.app/",
      points: [
        "Built a system that extracts structured data from PDF documents using NLP.",
        "Implemented text parsing and preprocessing pipelines for efficient retrieval.",
        "Automated workflows to reduce manual effort and improve accuracy.",
      ],
    },
    {
      name: "Personalized Financial Assistant",
      date: "Oct 2024",
      tech: ["MERN", "Docker", "JWT"],
      iconKey: "wallet",
      accent: "amber",
      github: "https://github.com/sahravi63/sahravi63-Personalized-Financial-Assistant.git",
      live: null,
      points: [
        "Built a full-stack expense tracking app with secure JWT authentication.",
        "Implemented encryption for sensitive financial data at rest.",
        "Containerized with Docker for scalability and reliable deployment.",
      ],
    },
    {
      name: "Movie Recommendation System",
      date: "2024",
      tech: ["Python", "NLP", "Scikit-learn"],
      iconKey: "clapperboard",
      accent: "cyan",
      github: "https://github.com/sahravi63/Movie-Recommendation-System",
      live: "https://movie-recommendation00.streamlit.app/",
      points: [
        "Built a content-based recommender using cosine similarity over TMDB data.",
        "Generated Top-5 personalized recommendations from user input.",
        "Deployed an interactive Streamlit app for real-time inference.",
      ],
    },
    {
      name: "DiagramToTextAI",
      date: "Mar 2025",
      tech: ["AI", "Computer Vision", "NLP"],
      iconKey: "scan-text",
      accent: "amber",
      github: "https://github.com/sahravi63/DiagramToTextAI",
      live: null,
      points: [
        "Developed an AI system that converts diagrammatic content into structured text.",
        "Combined image processing with NLP for semantic understanding.",
        "Enabled automated information extraction from visual diagrams.",
      ],
    },
  ],
  certifications: [
    {
      name: "AWS Certified Cloud Practitioner",
      issuer: "Amazon Web Services",
      validity: "Apr 2026 - Apr 2029",
      iconKey: "cloud",
      accent: "amber",
      badge: "https://www.credly.com/badges/33c9ff6c-d2f6-46c0-b52f-ade28382676a/public_url",
    },
    {
      name: "SAP Generative AI Developer",
      issuer: "SAP",
      validity: "Mar 2026 - Mar 2027",
      iconKey: "sparkles",
      accent: "cyan",
      badge: "https://www.credly.com/badges/9d168915-9215-4de5-9b9a-c5b86138fa98/public_url",
    },
    {
      name: "Oracle Cloud Infrastructure 2025 - GenAI Professional",
      issuer: "Oracle University",
      validity: "Oct 2025 - Oct 2027",
      iconKey: "database",
      accent: "amber",
      badge:
        "https://catalog-education.oracle.com/ords/certview/sharebadge?id=9A00A780137E8D85961B398A6770EB8DE9B1A5E989A6FD524557B3DA6720BD7B",
    },
    {
      name: "NPTEL: Introduction to Machine Learning",
      issuer: "IIT Kharagpur",
      validity: "Jul-Sep 2025 | Score 65% (Elite)",
      iconKey: "graduation-cap",
      accent: "cyan",
      certificate: true,
      score: { assignments: "22.92/25", exam: "41.84/75", total: "65%" },
    },
  ],
  achievements: [
    "Won Second Prize (INR 2,500) at SRM Intercollege Product Expo for an EV Monitoring System.",
    "Selected among the Top 100 teams in the JA Assure Hackathon, August 2024.",
  ],
  skills: {
    Languages: {
      accent: "cyan",
      items: [
        { name: "Python", iconKey: "code-2" },
        { name: "Java", iconKey: "coffee" },
        { name: "C/C++", iconKey: "terminal" },
        { name: "JavaScript", iconKey: "braces" },
        { name: "SQL", iconKey: "database" },
      ],
    },
    "ML & Data": {
      accent: "amber",
      items: [
        { name: "NLP", iconKey: "message-square-text" },
        { name: "Scikit-Learn", iconKey: "brain" },
        { name: "Pandas", iconKey: "table-2" },
        { name: "NumPy", iconKey: "sigma" },
        { name: "Matplotlib", iconKey: "line-chart" },
      ],
    },
    Web: {
      accent: "cyan",
      items: [
        { name: "React", iconKey: "atom" },
        { name: "Node.js", iconKey: "server" },
        { name: "CSS", iconKey: "palette" },
      ],
    },
    "Cloud & Tools": {
      accent: "amber",
      items: [
        { name: "AWS", iconKey: "cloud" },
        { name: "Docker", iconKey: "container" },
        { name: "Git", iconKey: "git-branch" },
        { name: "Oracle Cloud", iconKey: "hard-drive" },
        { name: "SAP", iconKey: "building-2" },
      ],
    },
    IDEs: {
      accent: "cyan",
      items: [
        { name: "VS Code", iconKey: "code" },
        { name: "PyCharm", iconKey: "squircle" },
        { name: "IntelliJ", iconKey: "layers" },
      ],
    },
  },
  navLinks: [
    { id: "about", label: "About" },
    { id: "skills", label: "Skills" },
    { id: "experience", label: "Experience" },
    { id: "projects", label: "Projects" },
    { id: "certifications", label: "Certifications" },
    { id: "contact", label: "Contact" },
  ],
};
